### ISSUE TITLE
odd behaviour with juice

### ISSUE THREAD

**Issue by ix0rai** [MarcusElg/More-Berries#10]
juice does not give you a glass bottle when drank or require a glass bottle to be crafted, even though the texture clearly shows it in a bottle. this just seems odd to me.

sidenote: honey bottles seem like the convention for a juicelike item, and they only stack to 16. I feel like it would be an improvement if juice from moreberries had parity with that.

**Comment by MarcusElg** [comment]
That does sound like a bug, they should be crafted with glass bottles and do give you it back

**Comment by MarcusElg** [comment]
![image](https://user-images.githubusercontent.com/19669673/158986802-9877ba54-51d0-410b-8945-ef7a552273f0.png)
You must be using an old version. They have required glass bottles to craft for a long time. It does make sense to change the stack limit tho so that will be implemented in the next update
